version: '3.9'
services:
  student-srv:
    build:
      context: .
    networks:
      - student-pub
      - student-priv
    ports:
      - target: 8080
        published: 8081
        protocol: tcp
        mode: host
    environment:
      - MYSQL_SERVER=student-db

    depends_on:
      - student-db

  student-db:
    image: mysql:5.6
    networks:
      - student-priv
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=bhanu
      - MYSQL_PASSWORD=root
    volumes:
      - type: volume
        source: student-vol
        target: /var/lib/mysql
volumes:
  student-vol:

networks:
  student-pub:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16
  student-priv:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.169.0.0/16
